Vagrant.configure("2") do |config|
    start_ip = 11
    (1..3).each do |i|
        config.vm.define "node#{i}" do |c|
            c.vm.box = "ubuntu/focal64"
            c.vm.hostname = "docker#{i}"
            c.vm.network "private_network", ip: "192.168.101.#{start_ip + i - 1}", name: "vboxnet0"
            c.vm.provider "virtualbox" do |vb|
                vb.memory = 4096
                vb.cpus = 2
                vb.customize ["modifyvm", :id, "--audiocontroller", "sb16"]
            end
            c.vm.provision "file", source: "key.pub", destination: "~/.ssh/me.pub"
            c.vm.provision "shell", inline: <<-SHELL
            cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
            SHELL
        end
    end
end